#!/usr/bin/env bash
# display dig info on a domain
show_subdomain () {
    line=$(dig $1 | awk 'c&&!--c;/ANSWER SECTION:/{c=1}')
    read -r sub rtype dest<<< $(echo "$line" | awk '{print $1, $4, $5}')
    sub=$(echo "$sub" | awk 'BEGIN {FS="."} {print $1} END{}')
    echo The subdomain "$sub" is a "$rtype" record and points to "$dest"
}
show_all () {
    subs=(www.$1 lb-01.$1 web-01.$1 web-02.$1)
    for sub in ${subs[@]}
    do
    show_subdomain $sub
    done
}
if [ ! -z $2 ]
then
show_subdomain $2.$1
else
show_all $1
fi
