#!/usr/bin/env bash
# install nginx server and change landing content
apt-get update -y
apt-get upgrade -y
apt-get install nginx -y
echo "Hello World!" > /usr/share/nginx/html/index.html
service nginx restart
