#!/usr/bin/env bash
# set /redirect_me to return 301
apt-get update -y
apt-get upgrade -y
apt-get install nginx -y
echo "Hello World" > /usr/share/nginx/html/index.html
num="$(grep -c -P '^\tlocation \/redirect_me' < /etc/nginx/sites-available/default)"
if [ "$num" -eq 0 ]
then
	sed -i '/^\tserver_name/ a\\n\tlocation \/redirect_me \{\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t\}\n' /etc/nginx/sites-available/default
fi
service nginx restart
