#!/usr/bin/env bash
# Install and Configure Nginx to serve Hello World on homepage and 
# redirct to youtube when redirect_me is access
apt-get update -y 
apt-get upgrade -y
apt-get install nginx -y
chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
line1="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "26i $line1" /etc/nginx/sites-available/default
mkdir -p /var/www/default
echo "Ceci n'est pas une page" > /var/www/default/404.html
line2="\\\tlocation = /404.html {\n\t\t root /var/www/default;\n\t}"
sed -i "29i $line2" /etc/nginx/sites-available/default
line3="\\\terror_page 404 /404.html;"
sed -i "32i $line3" /etc/nginx/sites-available/default
service nginx restart
