#!/usr/bin/env bash
# setup load balancer
add-apt-repository -y ppa:vbernat/haproxy-1.5
apt-get update
apt-get install -y haproxy

echo -e "frontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n" >> /etc/haproxy/haproxy.cfg
echo -e "backend http_back\n\tbalance roundrobin\n\tserver 57493-web-01 52.87.23.85:80 check\n\tserver 57493-web-02 34.232.71.168:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
