#!/usr/bin/env bash
# Displays 'To infinity and beyond' indefinitely
#+ and invincibles

trap "echo 'I an invincible!!!'" SIGTERM
while true;
do
        echo "To infinity and beyond"
        sleep 2
done
