#!/usr/bin/env bash
# This script displays 'Best School" with a condition if

i=0

while [ $i -lt 10 ]
do
        if [ $i -eq 9 ]
        then
                echo "Hi"
        fi
        echo "Best School"
        (( i = i + 1))
done 
