#!/usr/bin/env bash
# to check if school file exists, empty or regular

if [ -e school ]
then
        echo "school file exists"
        if [ -s school ]
        then
                echo "school file is not empty"
        else
                echo "school file is empty"
        fi

        if [ -f school ]
        then
                echo "school is a regular file"
        else
                echo -n 
        fi
else
        echo "school file does not exist"
fi
